project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - index.qmd
      - rdtesting.qmd
      - polmeth.qmd
      - software.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    
bibliography: website.bib
    

editor: visual

